#[env]
#TERM = "xterm-256color"

[window]
opacity = 0.89
decorations = "Full" #"Full" # "Buttonless" #"Transparent"


[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
normal = { family = "FiraCode Nerd Font"}
size = 13


[colors.primary]
background = "#000000"
